package com.trxk.scpww.pojo;

import java.util.List;

public interface JiFenXiaoFeiMapper {

    List<JiFenXiaoFei> selectByUserId (JiFenXiaoFei jiFenXiaoFei);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ji_fen_xiao_fei
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ji_fen_xiao_fei
     *
     * @mbg.generated
     */
    int insert(JiFenXiaoFei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ji_fen_xiao_fei
     *
     * @mbg.generated
     */
    int insertSelective(JiFenXiaoFei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ji_fen_xiao_fei
     *
     * @mbg.generated
     */
    JiFenXiaoFei selectByuserId(JiFenXiaoFei jiFenXiaoFei);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ji_fen_xiao_fei
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JiFenXiaoFei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ji_fen_xiao_fei
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JiFenXiaoFei record);
}