package com.trxk.scpww.pojo;

public interface JiFenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jifen
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long jifenid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jifen
     *
     * @mbg.generated
     */
    int insert(JiFen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jifen
     *
     * @mbg.generated
     */
    int insertSelective(JiFen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jifen
     *
     * @mbg.generated
     */
    JiFen selectByUserId(JiFen jiFen);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jifen
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JiFen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jifen
     *
     * @mbg.generated
     */
    void updateByUserId(JiFen record);
}