package com.trxk.scpww.pojo;

import java.util.Date;

public class JiFenXiaoFei {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ji_fen_xiao_fei.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ji_fen_xiao_fei.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ji_fen_xiao_fei.xiao_fei_ji_fen
     *
     * @mbg.generated
     */
    private Integer xiaoFeiJiFen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ji_fen_xiao_fei.shi_yong_shi_jian
     *
     * @mbg.generated
     */
    private Date shiYongShiJian;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ji_fen_xiao_fei.id
     *
     * @return the value of ji_fen_xiao_fei.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ji_fen_xiao_fei.id
     *
     * @param id the value for ji_fen_xiao_fei.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ji_fen_xiao_fei.user_id
     *
     * @return the value of ji_fen_xiao_fei.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ji_fen_xiao_fei.user_id
     *
     * @param userId the value for ji_fen_xiao_fei.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ji_fen_xiao_fei.xiao_fei_ji_fen
     *
     * @return the value of ji_fen_xiao_fei.xiao_fei_ji_fen
     *
     * @mbg.generated
     */
    public Integer getXiaoFeiJiFen() {
        return xiaoFeiJiFen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ji_fen_xiao_fei.xiao_fei_ji_fen
     *
     * @param xiaoFeiJiFen the value for ji_fen_xiao_fei.xiao_fei_ji_fen
     *
     * @mbg.generated
     */
    public void setXiaoFeiJiFen(Integer xiaoFeiJiFen) {
        this.xiaoFeiJiFen = xiaoFeiJiFen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ji_fen_xiao_fei.shi_yong_shi_jian
     *
     * @return the value of ji_fen_xiao_fei.shi_yong_shi_jian
     *
     * @mbg.generated
     */
    public Date getShiYongShiJian() {
        return shiYongShiJian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ji_fen_xiao_fei.shi_yong_shi_jian
     *
     * @param shiYongShiJian the value for ji_fen_xiao_fei.shi_yong_shi_jian
     *
     * @mbg.generated
     */
    public void setShiYongShiJian(Date shiYongShiJian) {
        this.shiYongShiJian = shiYongShiJian;
    }

    @Override
    public String toString()
    {
        return "JiFenXiaoFei{" +
                "id=" + id +
                ", userId='" + userId + '\'' +
                ", xiaoFeiJiFen=" + xiaoFeiJiFen +
                ", shiYongShiJian=" + shiYongShiJian +
                '}';
    }
}