package com.trxk.scpww.pojo;

import java.util.Date;
import java.util.List;

/**
 * @author huangjun
 */
public class Orders {

    private String id;
    private String trainCode;
    private String startStation;
    private String endStation;
    private String startTime;
    private Double ticketPrice;
    private Integer ticketNumber;
    private String ticketType;
    private Date createTime;
    private Integer payType;
    private Integer orderState;
    private String userId;

    private List<Passenger> passengerList;  

    public List<Passenger> getPassengerList() {
        return passengerList;
    }

    public void setPassengerList(List<Passenger> passengerList) {
        this.passengerList = passengerList;
    }

    public Orders() {
    }

    public Orders(String id, String trainCode, String startStation, String endStation, String startTime, Double ticketPrice, Integer ticketNumber, String ticketType, Date createTime, Integer payType, Integer orderState, String userId) {
        this.id = id;
        this.trainCode = trainCode;
        this.startStation = startStation;
        this.endStation = endStation;
        this.startTime = startTime;
        this.ticketPrice = ticketPrice;
        this.ticketNumber = ticketNumber;
        this.ticketType = ticketType;
        this.createTime = createTime;
        this.payType = payType;
        this.orderState = orderState;
        this.userId = userId;
    }

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.train_code
     *
     * @return the value of orders.train_code
     *
     * @mbg.generated
     */
    public String getTrainCode() {
        return trainCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.train_code
     *
     * @param trainCode the value for orders.train_code
     *
     * @mbg.generated
     */
    public void setTrainCode(String trainCode) {
        this.trainCode = trainCode == null ? null : trainCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.start_station
     *
     * @return the value of orders.start_station
     *
     * @mbg.generated
     */
    public String getStartStation() {
        return startStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.start_station
     *
     * @param startStation the value for orders.start_station
     *
     * @mbg.generated
     */
    public void setStartStation(String startStation) {
        this.startStation = startStation == null ? null : startStation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.end_station
     *
     * @return the value of orders.end_station
     *
     * @mbg.generated
     */
    public String getEndStation() {
        return endStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.end_station
     *
     * @param endStation the value for orders.end_station
     *
     * @mbg.generated
     */
    public void setEndStation(String endStation) {
        this.endStation = endStation == null ? null : endStation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.start_time
     *
     * @return the value of orders.start_time
     *
     * @mbg.generated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.start_time
     *
     * @param startTime the value for orders.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ticket_price
     *
     * @return the value of orders.ticket_price
     *
     * @mbg.generated
     */
    public Double getTicketPrice() {
        return ticketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ticket_price
     *
     * @param ticketPrice the value for orders.ticket_price
     *
     * @mbg.generated
     */
    public void setTicketPrice(Double ticketPrice) {
        this.ticketPrice = ticketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ticket_number
     *
     * @return the value of orders.ticket_number
     *
     * @mbg.generated
     */
    public Integer getTicketNumber() {
        return ticketNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ticket_number
     *
     * @param ticketNumber the value for orders.ticket_number
     *
     * @mbg.generated
     */
    public void setTicketNumber(Integer ticketNumber) {
        this.ticketNumber = ticketNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ticket_type
     *
     * @return the value of orders.ticket_type
     *
     * @mbg.generated
     */
    public String getTicketType() {
        return ticketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ticket_type
     *
     * @param ticketType the value for orders.ticket_type
     *
     * @mbg.generated
     */
    public void setTicketType(String ticketType) {
        this.ticketType = ticketType == null ? null : ticketType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_time
     *
     * @return the value of orders.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.create_time
     *
     * @param createTime the value for orders.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_type
     *
     * @return the value of orders.pay_type
     *
     * @mbg.generated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_type
     *
     * @param payType the value for orders.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_state
     *
     * @return the value of orders.order_state
     *
     * @mbg.generated
     */
    public Integer getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_state
     *
     * @param orderState the value for orders.order_state
     *
     * @mbg.generated
     */
    public void setOrderState(Integer orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param userId the value for orders.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}