package com.trxk.scpww.pojo;

import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.start_station
     *
     * @mbg.generated
     */
    private String startStation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.end_station
     *
     * @mbg.generated
     */
    private String endStation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.startTime
     *
     * @mbg.generated
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ticket_price
     *
     * @mbg.generated
     */
    private Double ticketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ticket_number
     *
     * @mbg.generated
     */
    private Integer ticketNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ticket_type
     *
     * @mbg.generated
     */
    private String ticketType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_state
     *
     * @mbg.generated
     */
    private Integer orderState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.start_station
     *
     * @return the value of orders.start_station
     *
     * @mbg.generated
     */
    public String getStartStation() {
        return startStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.start_station
     *
     * @param startStation the value for orders.start_station
     *
     * @mbg.generated
     */
    public void setStartStation(String startStation) {
        this.startStation = startStation == null ? null : startStation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.end_station
     *
     * @return the value of orders.end_station
     *
     * @mbg.generated
     */
    public String getEndStation() {
        return endStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.end_station
     *
     * @param endStation the value for orders.end_station
     *
     * @mbg.generated
     */
    public void setEndStation(String endStation) {
        this.endStation = endStation == null ? null : endStation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.startTime
     *
     * @return the value of orders.startTime
     *
     * @mbg.generated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.startTime
     *
     * @param starttime the value for orders.startTime
     *
     * @mbg.generated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ticket_price
     *
     * @return the value of orders.ticket_price
     *
     * @mbg.generated
     */
    public Double getTicketPrice() {
        return ticketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ticket_price
     *
     * @param ticketPrice the value for orders.ticket_price
     *
     * @mbg.generated
     */
    public void setTicketPrice(Double ticketPrice) {
        this.ticketPrice = ticketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ticket_number
     *
     * @return the value of orders.ticket_number
     *
     * @mbg.generated
     */
    public Integer getTicketNumber() {
        return ticketNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ticket_number
     *
     * @param ticketNumber the value for orders.ticket_number
     *
     * @mbg.generated
     */
    public void setTicketNumber(Integer ticketNumber) {
        this.ticketNumber = ticketNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ticket_type
     *
     * @return the value of orders.ticket_type
     *
     * @mbg.generated
     */
    public String getTicketType() {
        return ticketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ticket_type
     *
     * @param ticketType the value for orders.ticket_type
     *
     * @mbg.generated
     */
    public void setTicketType(String ticketType) {
        this.ticketType = ticketType == null ? null : ticketType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_time
     *
     * @return the value of orders.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.create_time
     *
     * @param createTime the value for orders.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_state
     *
     * @return the value of orders.order_state
     *
     * @mbg.generated
     */
    public Integer getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_state
     *
     * @param orderState the value for orders.order_state
     *
     * @mbg.generated
     */
    public void setOrderState(Integer orderState) {
        this.orderState = orderState;
    }
}