package com.trxk.scpww.pojo;

import java.util.List;

public interface PassengerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated
     */
    boolean insert(Passenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated
     */
    int insertSelective(Passenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated
     */
    Passenger selectByPrimaryKey(String id);


    List<Passenger> selectAllByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Passenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passenger
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Passenger record);

    /**
     * 根据常用乘车人姓名和身份证查询常用乘车人
     * @param passenger 常用乘车人
     * @return 查询出来的常用乘车人
     */
    Passenger selectPassengerByPassengernameAndIdentityNumber(Passenger passenger);
}