package com.trxk.scpww.pojo;

import java.util.Date;

public class Signin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.signin_time
     *
     * @mbg.generated
     */
    private Date signinTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.id
     *
     * @return the value of signin.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.id
     *
     * @param id the value for signin.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.user_id
     *
     * @return the value of signin.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.user_id
     *
     * @param userId the value for signin.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.signin_time
     *
     * @return the value of signin.signin_time
     *
     * @mbg.generated
     */
    public Date getSigninTime() {
        return signinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.signin_time
     *
     * @param signinTime the value for signin.signin_time
     *
     * @mbg.generated
     */
    public void setSigninTime(Date signinTime) {
        this.signinTime = signinTime;
    }
}