package com.trxk.scpww.pojo;

public interface SigninMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated
     */
    int insert(Signin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated
     */
    int insertSelective(Signin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated
     */
    Signin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Signin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Signin record);
}