package com.trxk.scpww.pojo;

public class UserPassenger {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_passenger.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_passenger.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_passenger.passenger_id
     *
     * @mbg.generated
     */
    private String passengerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_passenger.id
     *
     * @return the value of user_passenger.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_passenger.id
     *
     * @param id the value for user_passenger.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_passenger.user_id
     *
     * @return the value of user_passenger.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_passenger.user_id
     *
     * @param userId the value for user_passenger.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_passenger.passenger_id
     *
     * @return the value of user_passenger.passenger_id
     *
     * @mbg.generated
     */
    public String getPassengerId() {
        return passengerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_passenger.passenger_id
     *
     * @param passengerId the value for user_passenger.passenger_id
     *
     * @mbg.generated
     */
    public void setPassengerId(String passengerId) {
        this.passengerId = passengerId == null ? null : passengerId.trim();
    }
}