package com.trxk.scpww.pojo;

public interface UserPassengerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_passenger
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_passenger
     *
     * @mbg.generated
     */
    int insert(UserPassenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_passenger
     *
     * @mbg.generated
     */
    int insertSelective(UserPassenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_passenger
     *
     * @mbg.generated
     */
    UserPassenger selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_passenger
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserPassenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_passenger
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserPassenger record);
}